baseURL: 'https://oct.zoy.org/'
languageCode: en-us
title: oct.zoy.org
theme: PaperMod
env: production
ignoreLogs:
  - warning-goldmark-raw-html
menu:
  main:
    - identifier: archives
      name: ğŸ•°ï¸ Post Archive
      url: /archives/
      weight: 10
    - identifier: tags
      name: ğŸ”– tags
      url: /tags/
      weight: 20
    - identifier: about
      name: ğŸª about
      url: /about
      weight: 1
    - identifier: speaker
      name: ğŸ“¢ speaker
      url: /as-a-speaker
      weight: 2
    - identifier: Ã©crits
      name: ğŸ–‹ï¸ Ã‰crits
      url: /Ã©crits
      weight: 40
    - identifier: oldies
      name: ğŸ•¸ï¸ old stuff
      url: /old-stuff/
      weight: 50
imaging:
  anchor: Smart
  bgColor: '#ffffff'
  hint: photo
  quality: 75
  resampleFilter: Box
params:
  analytics:
    googlesiteVerificationTag: y8HjH28HsDJmfXel6OVWYfVTlOaM5Y0qt1sSIu4ncXo
  hideFooter: false
  showBreadCrumbs: true
  showReadingTime: true
  ShowCodeCopyButtons: true
  cover:
    responsiveImages: true
  mainSections:
    - posts
  label:
    icon: /bandana.png
  homeInfoParams:
    title: Welcome to my site!
    content: | 
      I'm Pierre Baillet (aka _Oct_), a programmer who's been in love with coding since my early days tinkering with an Atari ST and GFA-Basic.

      My digital playground is a bit chaotic - I create projects that are part passion, part experiment. Some stick around in production, some quietly fade away. But that's the beauty of coding, right? Always exploring, always learning.

      What you'll find here:

      * Bits of code and tech musings,
      * Projects that are more "works in progress" than polished gems
      * Thoughts shared in both English and French ğŸ‡¬ğŸ‡§ğŸ‡«ğŸ‡·

      Welcome to my little corner of the internet - where imperfect code meets endless curiosity!

      Coding isn't just what I do, it's who I am. ğŸ–¥ï¸
  profileMode:
    enabled: false
    buttons:
      - name: Posts
        url: /posts
      - name: Archive
        url: /archive
  socialIcons:
    - name: mastodon
      url: "https://mastodon.xyz/@octplane"
    - name: Github
      url: 'https://github.com/octplane'
