baseURL: 'https://oct.zoy.org/'
languageCode: en-us
title: oct.zoy.org
theme: PaperMod
env: production
ignoreLogs:
  - warning-goldmark-raw-html
menu:
  main:
    - identifier: about
      name: ğŸª About
      url: /about
      weight: 1
    - identifier: speaker
      name: ğŸ“¢ As a Speaker
      url: /as-a-speaker
      weight: 2
    - identifier: compos
      name: ğŸ¼ Compos
      url: /compos
      weight: 3
    - identifier: archives
      name: ğŸ•°ï¸ Post Archive
      url: /archives/
      weight: 10
    - identifier: tags
      name: ğŸ”– tags
      url: /tags/
      weight: 20
    - identifier: Ã©crits
      name: ğŸ–‹ï¸ Ã‰crits
      url: /Ã©crits
      weight: 40
    - identifier: oldies
      name: ğŸ•¸ï¸ Old stuff
      url: /old-stuff/
      weight: 50
imaging:
  anchor: Smart
  bgColor: '#ffffff'
  hint: photo
  quality: 75
  resampleFilter: Box
params:
  analytics:
    googlesiteVerificationTag: y8HjH28HsDJmfXel6OVWYfVTlOaM5Y0qt1sSIu4ncXo
  hideFooter: false
  showBreadCrumbs: true
  showReadingTime: true
  ShowCodeCopyButtons: true
  cover:
    responsiveImages: true
  mainSections:
    - posts
  label:
    icon: /bandana.png
  homeInfoParams:
    title: Welcome to my site!
    content: | 
      I'm Pierre Baillet (aka _Oct_), a programmer who's been in love with coding since my early days tinkering with an Atari ST and GFA-Basic.

      What you'll find here:

      * Bits of code and tech musings,
      * Projects that are more "works in progress" than polished gems
      * Some Music Composition
      * Thoughts shared in both English and French ğŸ‡¬ğŸ‡§ğŸ‡«ğŸ‡·

      Welcome to my little corner of the internet

      Coding isn't just what I do, it's who I am. ğŸ–¥ï¸
  profileMode:
    enabled: false
    buttons:
      - name: Posts
        url: /posts
      - name: Archive
        url: /archive
  socialIcons:
    - name: mastodon
      url: "https://mastodon.xyz/@octplane"
    - name: Github
      url: 'https://github.com/octplane'
